### ISSUE TITLE
(phi0010/__cts__.xml) Demande d'ajout de traduction

### ISSUE THREAD

**Issue by SybilleClochet** [PonteIneptique/canonical-greekLit#11]
Bonjour M. Clérice,
Dans le fichier (canonical-greefLit/data/phi0010/__cts__.xml), il manque la traduction en français du nom Isocrates.
Je vous propose de l'ajouter moi-même si cela vous convient.
Cordialement,
sybille clochet

**Comment by PonteIneptique** [comment]
Très bien, merci @SybilleClochet

**Comment by PonteIneptique** [comment]
Fixed by #16
