### ISSUE TITLE
(phi0019/__cts__.xml)Ajout de la traduction française du nom d'Aristophane

### ISSUE THREAD

**Issue by mggourio** [PonteIneptique/canonical-greekLit#13]
Ajout de la traduction française d'Aristophane dans le fichier https://github.com/PonteIneptique/canonical-greekLit/blob/master/data/tlg0019/__cts__.xml

**Comment by PonteIneptique** [comment]
Merci de la proposition ! Par contre, peut-être faudrait-il un titre plus évocateur ?

**Comment by PonteIneptique** [comment]
Fixed by #15
