### ISSUE TITLE
(tlg4036/__cts__.xml )Ajout de la traduction française du nom "Proclus"

### ISSUE THREAD

**Issue by Verronmere** [PonteIneptique/canonical-greekLit#41]
Ajout de la traduction française du nom "Proclus" [ici je voulais mettre "deux points" mais au lieu j'ai des notes, des +1 et etc et je ne peux pas garder que deux points  - dommage, au lieu je mets un tiré] -

 https://github.com/PonteIneptique/canonical-greekLit/blob/master/data/tlg4036/__cts__.xml

**Comment by PonteIneptique** [comment]
Fixed by #42
