### ISSUE TITLE
ajout de la traduction en français d'Eschyle et autres corrections

### ISSUE THREAD

**Issue by vasaura** [PonteIneptique/canonical-greekLit#8]
Ajout d'une traduction et autres propositions de corrections dans le fichier de métadonnées https://github.com/PonteIneptique/canonical-greekLit/blob/master/data/tlg0085/__cts__.xml
Le fichier contient deux fois la balise <ti:groupname xml:lang="eng">Aeschylus</ti:groupname> et une fois la même balise sans attribut de langue. Est-il volontaire?

**Comment by PonteIneptique** [comment]
Merci. Effectivement, ce dédoublement n'était pas volontaire. 

La correction a été réalisée, je ferme le ticket.
